### ISSUE TITLE
create trimmed redmapper/decals matched catalog

### ISSUE THREAD

**Issue by moustakas** [moustakas/siena-astrophysics#4]
Write out a table that just contains the matched objects (```objid != -1```).

**Comment by kjnapes** [comment]
This is done now. I have it on my local machine, but I need to somehow get it onto nyx. Any thoughts on how to do that without pushing the file to github?

**Comment by moustakas** [comment]
r sync should work.  Can you swing by my office before astro?  I want to
test the notebook again.

**Comment by kjnapes** [comment]
Yes I can. How early?

**Comment by moustakas** [comment]
Not too early.  9:20ish?

**Comment by kjnapes** [comment]
That sounds good.

**Comment by kjnapes** [comment]
File created; code pushed to github. Not yet tested, but it should be fine.
