### ISSUE TITLE
generate qaplots of redmapper/dr3 catalog

### ISSUE THREAD

**Issue by moustakas** [moustakas/siena-astrophysics#5]
We need a handful of plots to start defining the pilot sample:
* ra vs dec for full redmapper catalog and trimmed catalog
* richness vs redshift for trimmed catalog for spectroscopic clusters only
* think of other plots to make that will help us define a "pilot" sample (e.g., using imag, size, redshift, richness, etc.)
* look at decam_galdepth[2] and/or decam_nobs[2] to find clusters with deeper-than average depth or coverage

**Comment by kjnapes** [comment]
I know that at some point I plotted some various properties, but I'm not sure if I ever dug into the depth/coverage of the samples (maybe we started doing so at Kitt Peak?).

**Comment by moustakas** [comment]
Indeed we started looking at the depth and coverage in the `desitarget` product, but we never brought that code back to this project.

**Comment by moustakas** [comment]
This project---and therefore this issue---has moved to [legacyhalos](https://github.com/moustakas/legacyhalos).
