### ISSUE TITLE
download and match UPenn SDSS PhotDec catalog

### ISSUE THREAD

**Issue by moustakas** [moustakas/siena-astrophysics#6]
@kjnapes Here's the page for the photometric and stellar mass catalog we want to compare against -- if you could download and match against our SDSS/redmapper and SDSS/DECaLS redmapper and make some plots that'd be great:
http://alan-meert-website-aws.s3-website-us-east-1.amazonaws.com/fit_catalog/index.html

**Comment by moustakas** [comment]
Let's put the input catalogs and the resulting matched files in 
`/global/work/projects/legacysurvey/legacycentrals`
on nyx.

**Comment by kjnapes** [comment]
I am not sure if the matched catalog is in `/global/work/projects/legacysurvey/legacycentrals`, but I know that it is in my `kjnapes` directory.
